### ISSUE TITLE
Option w/default and block raises exception

### ISSUE THREAD

**Issue by MadBomber** [leejarvis/slop#163] opened 2015-03-17 14:20 UTC
This may actually be the prefered behavior but it was not what I expceted when I first used this construct.  Here is what I wanted to do:
```Ruby
o,string '-n','--name','print hello <name>', default: 'world' do |a_string|
  puts "Hello #{a_string}"
end
```
Instead of getting my expected "Hello world" I got an argument missing exception.  I can use the suppress_errors: true option to silence the exception BUT I get "Hello" without the expected default.

**Comment by leejarvis** [comment] 2015-03-17 15:23
I agree with you on the expected behaviour and I've marked this as a bug. Will fix it in a couple of hours. Thanks for reporting

**Comment by leejarvis** [comment] 2015-03-17 17:31
I'm actually not totally sure about this. The behaviour is actually probably what I would expect. i.e with the following code:

```ruby
o.string '--name', default: 'lee'
```

Then when the `--name` option is not supplied at all, it will default to `lee`. However, if you do `--name` without an argument, would you really expect it to be `lee`? What if you actually wanted a blank value? I'm not sure slop should handle this at the lowest level.

Here's a patch that adds the behaviour, whilst I'm mulling it over:

```diff
diff --git a/lib/slop/option.rb b/lib/slop/option.rb
index 218dc90..e197b1a 100644
--- a/lib/slop/option.rb
+++ b/lib/slop/option.rb
@@ -51,6 +51,7 @@ module Slop
         raise Slop::MissingArgument, "missing argument for #{flag}"
       end

+      value ||= default_value
       @value = call(value)
       block.call(@value) if block.respond_to?(:call)
     end
@@ -69,9 +70,11 @@ module Slop
     end

     # Override this if this option type does not expect an argument
-    # (i.e a boolean option type).
+    # (i.e a boolean option type). If a default value is present, the
+    # option does not *expect* an argument, since a potential fallback
+    # is available. It however, would accept one.
     def expects_argument?
-      true
+      !default_value
     end

     # Override this if you want to ignore the return value for an option
diff --git a/test/result_test.rb b/test/result_test.rb
index 760f460..a8d22b9 100644
--- a/test/result_test.rb
+++ b/test/result_test.rb
@@ -30,6 +30,9 @@ describe Slop::Result do
     @options.string("--foo", default: "bar")
     @result.parser.parse %w()
     assert_equal "bar", @result[:foo]
+
+    @result.parser.parse %w(--foo)
+    assert_equal "bar", @result[:foo]
   end

   it "handles custom finishing" do
```

**Comment by spk** [comment] 2015-05-23 11:16
For `optparse`, the option is set to `nil` when there is no argument. But there is no `default` option, you have to handle on your own how it should behave.

**Comment by brbrady** [comment] 2015-06-30 23:51
Hi @leejarvis, I just sent pull #174 for this, let me know what you think - I don't like the idea of changing `Option#expects_argument` since it's the easiest (only?) way to tell if an option takes an argument.

I also integrated your addition to result_test.rb from above into the pull request. :)

**Comment by leejarvis** [comment] 2016-01-22 09:28
Above PR merged

**Closed by leejarvis** 2016-01-22 09:28 UTC
Labels: bug
